#!/usr/bin/env escript
%% -*- erlang -*-
-mode(compile).

-import(lists, [foldl/3, filter/2, sort/1, foreach/2, sort/2]).

main(Args0) ->
    {Base,OutDir} = opts(Args0),
    io:format("Reading from ~p, writing output to ~p~n",
              [Base, OutDir]),
    Guards = read_gfiles(Base),
    TotalNoofFuns = maps:size(Guards),
    io:format("~p functions in total~n", [TotalNoofFuns]),
    InterestingGuards = maps:filter(fun(_, []) ->
                                            false;
                                       (_, [_,{true,_}]) ->
                                            false;
                                       (_, _) ->
                                            true
                                    end, Guards),
    io:format("~p with more than one guard~n", [maps:size(InterestingGuards)]),

    Hist = maps:fold(fun(_MFA, Gs, H) ->
                             N = length(Gs) - 1,
                             Old = maps:get(N, H, 0),
                             H#{N => Old + 1}
                     end, #{}, InterestingGuards),
    io:format("~p~n", [Hist]),
    ok.

usage() ->
    S = ["usage: qreport BASE_DIRECTORY OTHER_DIRECTORY OUTPUT_DIRECTORY\n\n"
         "Options:\n"
         "\n"
         "DESCRIPTION\n"
         "\n"
         "Compare the quality report files in two directories against each"
         " other\n"
        ],
    io:put_chars(S),
    halt(1).

opts([Base,Out]) ->
    {Base,Out};
opts(_) ->
    usage().

read_gfiles(Dir) ->
    read_pair_files(Dir, "*.G").

read_pair_files(Dir, Wildcard) ->
    foldl(fun(F, Data) ->
                  {ok,[D]} = file:consult(F),
                  maps:merge(maps:from_list(D), Data)
          end,
          #{},
          filelib:wildcard(filename:join(Dir, Wildcard))).
